### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by MehranDHN** [apdevelop/map-tile-service-asp-net-core#1]
Would you please provide the sample data to test this awesome project?

**Comment by apdevelop** [comment]
You can try this project using free [World Countries MBTiles](https://www.arcgis.com/home/item.html?id=7b650618563741ca9a5186c1aa69126e) set.

**Comment by brugner** [comment]
Hi @apdevelop, thanks for this project. I tried different maps from [Open Map Tiles](https://openmaptiles.com/downloads/planet/), but they don't seem to work. Only the one you provided works. Any ideas why?

**Comment by apdevelop** [comment]
Did you try [Satellite Lowres raster tiles Planet](https://openmaptiles.com/downloads/dataset/satellite-lowres/) ? This project support only serving **raster** tiles from MBTiles databases.
